In [47]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')


In [49]:
df=sns.load_dataset('iris')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
df.duplicated().sum()

1

In [7]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [15]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
lb.fit_transform(df['species'])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
df = sns.load_dataset('titanic')

In [21]:
df['embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [23]:
lb.fit_transform(df['class'])

array([2, 0, 2, 0, 2, 2, 0, 2, 2, 1, 2, 0, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1,
       2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 0, 0, 1, 2, 1, 2, 2, 0, 0, 2, 0, 2,
       1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 1, 2, 2, 2,
       0, 2, 2, 2, 0, 2, 2, 2, 0, 0, 1, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 1, 1, 0, 0, 2, 0, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 0, 2, 2,
       2, 0, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2,
       2, 0, 1, 2, 2, 1, 2, 1, 2, 0, 2, 0, 2, 2, 1, 1, 2, 1, 0, 0, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 1, 2, 1, 2, 0, 2, 1, 0, 1,
       2, 1, 2, 2, 0, 2, 1, 2, 1, 2, 0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2,
       1, 2, 2, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 1, 2, 2, 0, 0,
       2, 1, 2, 2, 0, 0, 0, 2, 1, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 1, 2, 0, 0, 1, 2, 2, 0, 2, 0, 0, 0, 2,

In [25]:
df['class']=lb.fit_transform(df['class'])

In [27]:
df['class'].unique()

array([2, 0, 1])

In [29]:
df['who']

0        man
1      woman
2      woman
3      woman
4        man
       ...  
886      man
887    woman
888    woman
889      man
890      man
Name: who, Length: 891, dtype: object

In [31]:
lb.fit_transform(df['who'])

array([1, 2, 2, 2, 1, 1, 1, 0, 2, 0, 0, 2, 1, 1, 0, 2, 0, 1, 2, 2, 1, 1,
       0, 1, 0, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 0, 2, 2, 1, 0,
       2, 1, 1, 2, 1, 2, 0, 1, 2, 2, 1, 1, 2, 1, 0, 0, 1, 2, 1, 0, 1, 1,
       2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 2, 1, 2, 2, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2,
       1, 0, 1, 2, 2, 1, 1, 1, 1, 0, 1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1,
       2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 0, 0, 2, 2, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 2, 1, 1, 2, 1, 0, 0, 0, 1, 2, 1, 1, 1, 2, 1, 2, 0, 2, 2, 1, 1,
       2, 2, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 1, 0, 1, 1, 2, 2,
       1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 0, 1, 1,
       2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 0, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 0, 1, 2, 2,

In [33]:
df['who']=lb.fit_transform(df['who'])

In [35]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0           0       3    male  22.0      1      0   7.2500        S      2   
1           1       1  female  38.0      1      0  71.2833        C      0   
2           1       3  female  26.0      0      0   7.9250        S      2   
3           1       1  female  35.0      1      0  53.1000        S      0   
4           0       3    male  35.0      0      0   8.0500        S      2   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
886         0       2    male  27.0      0      0  13.0000        S      1   
887         1       1  female  19.0      0      0  30.0000        S      0   
888         0       3  female   NaN      1      2  23.4500        S      2   
889         1       1    male  26.0      0      0  30.0000        C      0   
890         0       3    male  32.0      0      0   7.7500        Q      2   

     who  adult_male deck  embark_town alive  alone  
0      1        True  NaN  Southampton    no  False  
1      2       False    C    Cherbourg   yes  False  
2      2       False  NaN  Southampton   yes   True  
3      2       False    C  Southampton   yes  False  
4      1        True  NaN  Southampton    no   True  
..   ...         ...  ...          ...   ...    ...  
886    1        True  NaN  Southampton    no   True  
887    2       False    B  Southampton   yes   True  
888    2       False  NaN  Southampton    no  False  
889    1        True    C    Cherbourg   yes   True  
890    1        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [37]:
df['who'].unique()

array([1, 2, 0])

In [39]:
df['who'].unique()
df['who']=lb.fit_transform(df['who'])
print('After ',df['embark_town'].unique())


After  ['Southampton' 'Cherbourg' 'Queenstown' nan]


In [41]:
print('Before ',df['embark_town'].unique())
df['embark_town']=lb.fit_transform(df['embark_town'])
print('After ',df['embark_town'].unique())

Before  ['Southampton' 'Cherbourg' 'Queenstown' nan]
After  [2 0 1 3]


In [43]:
print('Before ',df['alive'].unique())
df['alive']=lb.fit_transform(df['alive'])
print('After ',df['alive'].unique())

Before  ['no' 'yes']
After  [0 1]


In [45]:
print('Before ',df['who'].unique())
df['who']=lb.fit_transform(df['who'])
print('After ',df['who'].unique())

Before  [1 2 0]
After  [1 2 0]
